import { VAULT_NOT_DEPLOYED } from "@masayume/core/vault";

/** Session-key tap-trading, the sponsor rail and the Ticket's funding source. */
export const SESSION = {
  notDeployed: VAULT_NOT_DEPLOYED,
  chip: {
    on: "tap-trading on",
    off: "tap-trading",
    needsKey: "tap-trading · needs a key",
    expired: "tap-trading · expired",
    titleOn: "Taps sign from a session key inside the caps you set. Open to see them.",
    titleOff: "Arm popup-free taps inside caps you set, funded from your Trading Balance.",
    titleNeedsKey: "A session grant is live but this browser holds no key for it. Open to revoke or re-key.",
    titleExpired: "The session grant expired. Open to arm a new one.",
    titleNoWallet: "Connect a wallet to arm tap-trading.",
  },
  route: {
    label: "Pay from",
    wallet: "Wallet",
    vault: "Trading Balance",
    vaultEmpty: "Your Trading Balance is empty — deposit on Portfolio first.",
    armedLocked: "Tap-trading is on: taps come from your Vault.",
    fromVault: "betting from your Vault",
    fromWallet: "betting from your wallet",
    fromGrant: (headroomText: string) => `betting from your Vault · ${headroomText} left today`,
    vaultNote: (availableText: string) => `Escrow comes from your Trading Balance (${availableText}); the fill is what the vault books.`,
    fallback: (reason: string) => `Tap-trading can't cover this one — ${reason}. Signing from your wallet instead.`,
  },
  sheet: {
    title: "Arm tap-trading",
    intro: "Deposit into your Trading Balance and hand a browser key the right to tap inside these caps. The key can never withdraw; only your wallet can.",
    perTrade: "Per tap",
    daily: "Per day",
    positions: "Open Windows",
    price: "Dearest odds",
    priceHint: "Never pays more than this per contract, in the side's own terms.",
    expiry: "Expires in",
    deposit: "Deposit now",
    depositHint: "Moves into your Trading Balance and becomes the key's budget.",
    budgetEqualsDeposit: "The grant's budget is this deposit.",
    example: (perTap: string, taps: number, daily: string, budget: string) =>
      `At ${perTap} a tap the key can place ${taps} ${taps === 1 ? "tap" : "taps"} today before the ${daily} daily cap stops it; the ${budget} budget covers exactly that.`,
    exampleShortBudget: (perTap: string, taps: number, budget: string) => `At ${perTap} a tap the ${budget} budget runs out after ${taps} ${taps === 1 ? "tap" : "taps"} — the daily cap never binds.`,
    resets: "Daily caps reset at 00:00 UTC.",
    receiptTitle: "What you are signing",
    receipt: {
      scope: "Scope",
      scopeValue: "Buy Up or Down on any live Window, from your Trading Balance",
      cannot: "Never",
      cannotValue: "withdraw, change where money goes, or spend past the caps",
      key: "Key",
      expiresAt: "Expires",
      gas: "Gas",
      gasSponsor: "paid by the sponsor; the key holds no STT",
      gasKey: (amountText: string) => `paid by the key — ${amountText} STT moves to it now`,
      signatures: "Signatures",
      sigsOne: "one: the deposit and grant, together",
      sigsTwo: "two: approve tUSDC, then the deposit and grant",
      sigsTopUp: (base: string) => `${base}, then one more to move STT to the key`,
    },
    cta: "Arm tap-trading",
    ctaBusy: "Arming…",
    ctaTopUp: "Moving STT to the key…",
    armed: "Tap-trading is on.",
    armedBody: "Taps on this browser sign from the session key inside your caps.",
    errors: {
      perTrade: "Per-tap cap must be at least the minimum stake.",
      daily: "Daily cap must be at least the per-tap cap.",
      deposit: "Deposit at least the per-tap cap.",
      price: "Dearest odds must be between 1¢ and 99¢.",
      positions: "Allow at least one open Window.",
      walletShort: (haveText: string) => `Your wallet holds ${haveText}; lower the deposit or use the faucet.`,
    },
  },
  manager: {
    title: "Tap-trading",
    key: "Key",
    scope: "Scope",
    caps: "Caps",
    capsValue: (perTap: string, daily: string, positions: number, price: string | null) =>
      `${perTap} per tap · ${daily} per day · ${positions} open ${positions === 1 ? "Window" : "Windows"}${price ? ` · dearest ${price}` : ""}`,
    spentToday: "Spent today",
    headroom: "Left today",
    budget: "Budget left",
    expires: "Expires",
    resets: "resets 00:00 UTC",
    gas: "Gas",
    gasSponsor: (sponsorText: string) => `sponsored by ${sponsorText}`,
    gasSponsorDeclined: (reason: string) => `the sponsor declined the last tap (${reason}); the key paid`,
    gasKey: (balanceText: string, taps: number) => `the key pays — holds ${balanceText} STT, enough for ${taps} ${taps === 1 ? "tap" : "taps"} at the ceiling`,
    gasKeyEmpty: "the key pays and holds no STT — top it up or taps will fall back to your wallet",
    topUp: (amountText: string) => `Move ${amountText} STT to the key`,
    revoke: "Revoke",
    revoking: "Revoking…",
    revokeNote: "One signature. The unspent budget returns to your Trading Balance; positions the key opened stay yours.",
    needsKeyTitle: "A grant with no key",
    needsKeyBody: "The vault holds a live session grant for a key this browser does not have — cleared storage, or another browser. Revoke it, or re-key: a new grant to a fresh key with the same caps and budget.",
    rekey: "Re-key",
    rekeying: "Re-keying…",
    expiredTitle: "The grant expired",
    expiredBody: "Nothing can tap from it any more. Arm a new one when you want popup-free taps again.",
    forget: "Forget this key",
    forgetNote: "Deletes the key from this browser. Do it after revoking — a live grant with no key just sits there.",
    armNew: "Arm tap-trading",
  },
  recovery: {
    title: "Session key",
  },
  dev: {
    title: "Session key",
    intro: "Every state of the chip, the route control, the enable sheet and the manager, from canned views. Nothing here signs.",
    states: "Chip and manager",
    route: "Pay-from control",
    sheet: "Enable sheet",
    live: "Live — the connected wallet",
  },
} as const;
