/** `/strategies` and `/agents` — the reference's words (`app/strategies/page.tsx`, `components/LiveDesk.tsx`, `app/agents/page.tsx`), facts adapted to DreamDEX. */
export const STRATEGIES = {
  title: "Strategies",
  headline: "AI strategies.",
  counts: { listed: "listed", copying: "copying" },
  notDeployed: {
    eyebrow: "Desk",
    title: "Strategies",
    body: "Discover, inspect, and subscribe to strategies, with the verified trade history behind each one. A strategy executes only inside limits you set and can revoke.",
    dependency: "the StrategyRegistry contract — deploy with contracts/script/DeployStrategyRegistry.s.sol, then pnpm contracts:export",
  },
  desk: {
    autopilot: "⊙ Autopilot",
    what: (asset: string) => `An automated strategy that follows ${asset}'s trend, up or down.`,
    share: "Share this strategy on X",
    record: { title: "Track record", meta: (n: number) => `${n} trades · public`, winRate: "win rate", won: "Won", lost: "Lost", net: "Net so far" },
    disconnectedNote: "Withdraw anytime · testnet · you can lose what you put on.",
    joined: { eyebrow: "⊙ You're on the desk", body: (name: string) => `You're following ${name} now. Its next trade carries you.`, receipt: "your join receipt ↗" },
    status: {
      checking: "Checking the desk",
      offline: "Desk offline · not trading",
      neverStarted: "Desk never started · not trading",
      unknown: "Desk status unknown · store offline",
      watching: (asset: string) => `Copying · watching ${asset}`,
      signal: (side: string) => `Copying · ${side} signal`,
      stale: "Reconnect needed",
    },
    yourBalance: "Your desk balance",
    onlyYou: "only you can withdraw",
    yourLimits: "Your limits",
    perTrade: "/ trade",
    open: (n: number, cap: number) => `${n}/${cap} open`,
    enforced: "enforced on-chain",
    usedToday: (used: string, cap: string) => `${used} / ${cap} today`,
    resets: "resets 00:00 UTC",
    stale: {
      eyebrow: "Reconnect your desk",
      body: (balance: string) => `The desk moved to a new runner key, so it cannot trade for you until you re-authorize it. Your ${balance} has not moved and only you can withdraw it. This just says who is allowed to trade.`,
      cta: "Reconnect →",
    },
    underfunded: {
      eyebrow: "Your copying is paused",
      body: (have: string, cost: string, topUp: string) => `You have ${have} on the desk. Trades cost about ${cost}, so the desk is skipping every one. Top up to about ${topUp} and it starts trading for you again.`,
      cta: "Top up to resume →",
    },
    manage: { add: "+ Add money", withdraw: "Withdraw", caps: "Limits", pause: "Pause", pausing: "Pausing…" },
    addHint: (wallet: string) => `Wallet: ${wallet}`,
    withdrawHint: "Goes to your connected wallet. Nobody else's.",
    addCta: "Add to desk →",
    adding: "Adding…",
    withdrawing: "Withdrawing…",
    saveCaps: (mode: string) => `Save ${mode} limits →`,
    signing: "Signing…",
    paused: { title: "Paused · no new trades", body: (balance: string) => `Your ${balance} stays yours. Resume with one signature, or take it back below.`, resume: (cap: string) => `Resume copying: ≤ ${cap} / trade` },
    join: {
      collapsed: "Copy this strategy →",
      question: "How much goes on the desk?",
      back: "back",
      emptyWallet: "Wallet empty, no problem:",
      faucet: "Get free tUSDC →",
      already: (n: string) => `Already on the desk: ${n}. Leave empty to copy with just that.`,
      belowCost: (n: string) => `Trades here cost about ${n}. Below that you get skipped.`,
      maxPerTrade: (n: string) => `${n} max per trade`,
      change: "change per-trade limit",
      done: "done",
      busy: "Two signatures…",
      floor: (n: string) => `Put on at least ${n} to copy`,
      put: (n: string) => `Put ${n} on & copy →`,
      withBalance: (n: string) => `Copy with your ${n} →`,
      floorNote: (n: string) => `Needs about ${n} to place a trade.`,
      twoSignatures: "Two signatures: the first funds your Vault and sets your limits, the second subscribes.",
    },
    risk: { title: "Risk mode", guarded: ["Guarded", "1 open · price ≤ 0.70"], balanced: ["Balanced", "1 open · price ≤ 0.85"], active: ["Active", "up to 2 open · any price"] },
    capsLabel: "Most it may risk per trade",
    suggested: (n: string) => `${n} (suggested)`,
  },
  x: { linked: (h: string) => `@${h} linked`, title: "Strategies on X", sub: "Link your account, then discover strategies in your feed.", connect: "Connect X", browse: "Browse on X" },
  archive: {
    title: "Earlier agents",
    editions: (n: number) => `${n} archived editions`,
    show: (n: number) => `View archive · ${n}`,
    hide: "Hide archive",
    reading: "reading the chain…",
    ledger: "Masayume Ledger",
    noneTitle: "No editions filed yet",
    noTab: (tab: string) => `No ${tab} agents`,
    noneBody: "Copyable agents appear here the moment a creator publishes one. Every agent is bound to hard risk caps on-chain before a dollar of yours can move.",
    noMatch: "Nothing matches this filter yet. Try another tab.",
    unreachable: "Couldn't reach the chain. Retrying every 30s.",
    instinct: (asset: string) => `follows the ${asset} trend · up or down`,
    max: "max",
    netMeta: (n: number) => `net · ${n} settled`,
    archived: "listed",
    memory: "◈ agent memory",
    playbook: "▤ saved playbook",
    foot: (max: string, fee: string, copiers: string) => `max ${max} · ${fee}${copiers}`,
    free: "free",
    yourPosition: "your position",
    copy: "copy on the desk",
  },
  tiers: { settled: (n: number) => `Settled · ${n} closed`, active: (n: number) => `Active · ${n} copy-trades`, copying: (n: number) => `${n} copying · no fills yet`, fresh: "New · no track record yet" },
  tabs: { all: "All", settled: "Settled", memwal: "Has playbook", copied: "Most copied", safest: "Safest", new: "New" },
  recent: { title: "Recent copy-trades", empty: "No copy-trades settled yet. Be the first.", copied: (n: number) => `copied ×${n}`, viewAll: (n: number) => `View all ${n} on-chain ↗`, storeOff: "The fill store is not connected on this deployment; fills are read from the runner's receipts once it is." },
  studio: {
    eyebrow: "Creator studio",
    title: "Launch an agent",
    soon: "Coming soon",
    sensei: "Meet Sensei →",
    launch: "Launch an agent",
    steps: { strategy: ["01", "Strategy", "the instinct it trades on"], tune: ["02", "Tune", "two knobs. Everything else is fixed and reviewed"], caps: ["03", "Hard limits", "the ceilings it is bound to on-chain, forever"], who: ["04", "Who runs it"] },
    selected: "Selected",
    soonMomentum: "Soon · momentum runs today",
    lookback: "Lookback",
    rounds: "rounds",
    lookbackHint: "how far back it reads",
    threshold: "Threshold",
    thresholdHint: "smallest move worth a bet",
    plain: "In plain words",
    perTrade: "Most per trade",
    daily: "Most per day",
    feeLabel: "Subscription fee",
    hosting: {
      house: ["Recommended", "Let Masayume run it", "Masayume runs it for you, hands-off. Your caps live in the vault contract: it can trade copiers' funds, never take them."],
      self: ["Advanced", "Run your own bot", "You host the agent and hold its key. Register its wallet; it copies under the same limits enforced on-chain."],
    },
    agentWallet: "Agent wallet",
    agentPlaceholder: "0x… your bot's address",
    preview: "Preview",
    yourAgent: "Your agent",
    cap: (n: string) => `${n} cap`,
    subFee: "Sub fee",
    publish: "Publish strategy",
    launching: "launching…",
    note: "Limits are enforced on-chain. The agent trades only inside them and can never withdraw a copier's funds.",
    houseRunnerMissing: "No house runner is configured on this deployment (STRATEGY_RUNNER_ADDRESS); run your own bot instead.",
    playbook: "Playbook",
    playbookHint: "plain text, published in the open — nothing here is encrypted",
  },
  memory: {
    eyebrow: "⊙ The Memory Market",
    title: ["Own what an agent", "has learned."] as const,
    soonTitle: "More minds soon",
    soonBody: "Creators list their own agent's memory · self-serve, next",
    honest: "Sealed, purchasable playbooks need an encrypted store this deployment does not have. Playbooks here are plain text every visitor can read from the strategy card.",
  },
  disclosure: (asset: string) => `Agents trade tUSDC on Somnia testnet, on fast ${asset} up/down Windows. You can lose your full budget. The agent cannot withdraw or divert it. Verify every position on-chain.`,
  drawer: {
    record: "On-chain record ↗",
    guarantee: { eyebrow: "It can't touch your funds", body: "Your balance stays in your Vault. The agent can open positions for you under hard caps, but it", strong: "cannot withdraw or divert it.", verify: "verify limits on-chain ↗" },
    how: { eyebrow: "How it trades", body: (max: string, asset: string) => `Each time this agent trades it makes a ${asset} up/down call on its read of the print. Every call opens a position`, own: "you own", tail: (max: string) => `, capped at ${max} per trade. It pays out to you on settlement. It's a directional bet. It can win or lose.` },
    caps: { perTrade: "Most / trade", daily: "Most / day", fee: "Fee", free: "Free", copiers: "Copiers", trades: "Copy-trades", last: "Last active", none: "no trades yet" },
    playbook: { eyebrow: "▤ Playbook", body: "The creator's own notes on how it trades, in plain text. They guide the runner's spec; they can never touch your funds." },
    young: "Young strategy, short track record. Size accordingly.",
    copying: { eyebrow: "Copying", body: (cap: string) => `This agent's signals are copied into your Vault: up to ${cap} each, every position yours.`, pauseNote: "Pause stops new copies. Your open positions keep running and stay yours. The agent can't claim their proceeds out from under you.", pause: "Pause copying", pausing: "pausing…" },
    budget: { label: "Copy Balance", inVault: (n: string) => `in vault: ${n}`, note: "Add funds to your Vault's strategy budget. Your budget stays at risk until you withdraw or pause.", limit: "Your limit. Edit anytime. Pause anytime.", max: "max" },
    example: {
      set: (target: string, cap: string) => ({ target, cap }),
      valid: "copy balance. This agent can put at most",
      validTail: "on each copied trade. It can never exceed that cap. It can never withdraw your balance.",
      invalid: (cap: string) => `Set a copy balance. This agent puts at most ${cap} on each trade. Never more, and it can never withdraw your balance.`,
      addNow: "Add now",
      walletNeeded: "Wallet needed",
    },
    risk: "Copied trades can lose money. Only fund what you can afford to lose.",
    cta: { starting: "Starting…", enter: "Enter an amount", add: (n: string) => `Add ${n} & start copying`, current: "Start copying with current Copy Balance" },
    share: "Share this agent",
    close: "Close",
  },
  health: { neverStarted: "never started", alive: "alive", stale: "dead", unknown: "status unknown — ops offline", storeOff: "status unknown — no heartbeat store on this deployment" },
  errors: { read: "The registry could not be read right now.", fills: "The fill store could not be read right now." },
} as const;

export const AGENTS = {
  title: "Agents",
  crumb: { root: "Masayume", here: "Agents" },
  headline: "Agent Leaderboard",
  intro:
    "The runner keys that execute copy-trade strategies, ranked by the capital subscribers have entrusted to them and the copy-trades they have actually executed. Win-rate is left out on purpose. It is a vanity metric. Realized results (net after fees, drawdown) populate here as positions settle. The desk is early: today this reflects on-chain copy-trades to date, read straight from the chain and the runner's receipts.",
  reading: "reading the chain…",
  stats: { agents: "Agents", strategies: "Strategies", subscribers: "Subscribers", subscribersSub: "across all strategies", volume: "Capital deployed", volumeSub: "tUSDC notional" },
  desk: { index: "01", title: "The desk", meta: (n: number) => `${n} agents`, top: "Top Desk", strategies: (n: number) => `${n} strateg${n === 1 ? "y" : "ies"}`, subscribers: (n: number) => `${n} subscriber${n === 1 ? "" : "s"}`, entrusted: "Capital entrusted", copyTrades: "Copy-trades", maxPerTrade: "Max per trade", lastActive: "Last active" },
  empty: { title: "No agents on the desk yet", body: "Agents appear here as creators publish strategies and copy-trades execute on subscriber funds. The ranking is derived from the registry and the runner's receipts." },
  how: {
    index: "02",
    title: "How agents are ranked",
    rules: [
      ["Ranked on ", "entrusted capital", " and ", "executed copy-trades", ". The agent has to actually put subscriber capital to work to climb, so the order reflects skin in the game."],
      ["Hard ", "on-chain risk caps", " are shown per agent (max per trade is the widest ceiling across its strategies); the vault enforces them on every position."],
      ["", "No-divert custody", ". Agents never hold subscriber funds. Every position is owned by the subscriber and settles to them, so a creator can never divert a cent."],
      ["", "Win-rate is deliberately excluded.", " Verified realized results come from settled positions and populate as the desk matures."],
    ] as const,
  },
  notDeployed: { dependency: "the StrategyRegistry contract (the fill projection it ranks with is live)" },
} as const;
