/** `/leaderboard` — ported from the reference's leaderboard page; facts adapted to DreamDEX. */
export const LEADERBOARD = {
  title: "Leaderboard",
  hero: {
    eyebrow: "Everyone trading on DreamDEX",
    title: ["The", "house", "of names."] as const,
    traders: "Traders on DreamDEX · 24h",
    staked: "Total staked · top 50",
    nextClose: "Next market closes in",
    stamp: "TODAY'S BOARD",
    stampSub: "ROLLING",
    assets: "All assets",
    period: "Last 24 hours",
    closedCalls: (n: number) => `${n.toLocaleString()} closed calls · full day`,
    counting: "counting recent closes",
    partial: (n: number) => `${n.toLocaleString()} closed calls · partial day`,
  },
  loading: "Reading on-chain trade data…",
  empty: {
    headline: "No closed calls in this window yet.",
    body: "The board ranks players by real profit, so names show up once bets settle. Check back after the next few rounds settle.",
  },
  failed: "The board could not be read right now.",
  retry: "Try again",
  podium: {
    number: "01",
    title: "The podium",
    desc: "The top three on DreamDEX by profit over the last 24 hours, whoever they traded through.",
    ordinals: { 1: "1ST", 2: "2ND", 3: "3RD" } as Record<1 | 2 | 3, string>,
    sash: "GRAND CHAMPION",
    streak: (n: number) => `${n} WIN STREAK`,
    challenger: "CHALLENGER",
    contender: "CONTENDER",
  },
  field: {
    number: "02",
    title: "The field",
    desc: "Ranks four onward, ordered by profit.",
    meta: "rolling 24h",
    strip: { ranks: "RANKS 04-50", center: "LAST 24 HOURS · PROFIT", right: "CLOSED CALLS" },
    heads: { east: "Ranked account", center: "RANKS", west: "Ranked account" },
    dividers: { rankAndFile: "RANK & FILE", longTail: "THE LONG TAIL" },
    cellMeta: (rank: number, calls: number, winRate: number) => `#${rank} · ${calls} calls · ${winRate}% wins`,
  },
  you: {
    rank: "Your rank",
    unranked: "Unranked",
    of: (n: string) => `of ${n} on the venue`,
    name: (short: string) => `You · ${short}`,
    top: (pct: number) => `top ${pct}%`,
    none: "no closed calls in the last 24 hours",
    net: "Net",
    winRate: "Win rate",
    streak: "Streak",
    cta: "Your ledger →",
  },
  dash: "—",
  errors: { compute: "The board could not be computed." },
} as const;
