/**
 * Regenerates what `packages/markets` consumes from this workspace (AD-10):
 *   - src/contracts/<name>.abi.ts   from forge's `out/` (run `forge build` first)
 *   - src/addresses.masayume.json   from `deployments/<chainId>.json`
 * Nothing else in the monorepo reads `out/` or `deployments/` directly.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "packages", "markets", "src");
const contracts = [
  { name: "event-vault", artifact: "EventVault.sol/EventVault.json", exportName: "eventVaultAbi" },
  { name: "forwarder", artifact: "ERC2771Forwarder.sol/ERC2771Forwarder.json", exportName: "forwarderAbi" },
];

mkdirSync(join(target, "contracts"), { recursive: true });
for (const { name, artifact, exportName } of contracts) {
  const path = join(here, "out", artifact);
  if (!existsSync(path)) throw new Error(`missing ${path} — run forge build first`);
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  // One ABI entry per line: readable in a diff, and a generated file stays inside the file-length invariant.
  const entries = abi.map((entry) => `  ${JSON.stringify(entry)},`).join("\n");
  const body = `// Generated by contracts/export.mjs from forge output — do not edit.\nexport const ${exportName} = [\n${entries}\n] as const;\n`;
  writeFileSync(join(target, "contracts", `${name}.abi.ts`), body);
}

const deployments = {};
const dir = join(here, "deployments");
if (existsSync(dir)) {
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const record = JSON.parse(readFileSync(join(dir, file), "utf8"));
    deployments[String(record.chainId)] = { eventVault: record.eventVault, forwarder: record.forwarder, collateral: record.collateral };
  }
}
writeFileSync(join(target, "addresses.masayume.json"), `${JSON.stringify({ generatedBy: "contracts/export.mjs", deployments }, null, 2)}\n`);
console.log(`exported ${contracts.length} ABIs, ${Object.keys(deployments).length} deployment(s)`);
